# Generated by Django 5.1.1 on 2024-09-25 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
                ('id_proof1', models.ImageField(upload_to='id_proofs/')),
                ('rfid_ref_no', models.CharField(max_length=50, unique=True)),
                ('gatepass_id', models.CharField(max_length=50, unique=True)),
                ('aprt_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
