# Generated by Django 5.1.1 on 2024-09-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_rename_vistor_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfid_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatepass_id', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('place_of_visit', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=225, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('id_proof1', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('proof_type', models.CharField(choices=[(1, 'Aadhar'), (2, 'Driving License'), (3, 'Option 3'), (4, 'Option 4')], max_length=50, null=True)),
                ('aprt_name', models.TextField()),
                ('purpose', models.TextField()),
                ('visit_person', models.CharField(max_length=225, null=True)),
                ('in_time', models.TimeField(auto_now_add=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('visiting_mobile', models.CharField(max_length=225, null=True)),
                ('date', models.DateField()),
                ('extra_visitor', models.IntegerField()),
                ('has_vehicle', models.BooleanField(default=False)),
                ('id_number', models.CharField(max_length=26, null=True)),
                ('date_of_birth', models.CharField(max_length=26, null=True)),
                ('type_of_pass', models.CharField(max_length=10, null=True)),
                ('expiry_status', models.CharField(max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=100)),
                ('pass_type', models.CharField(max_length=10, null=True)),
                ('expiry_time', models.TimeField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=50)),
                ('rfid_ref_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.rfid_register')),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
