# Generated by Django 5.1.1 on 2024-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_rfid_register_visitortable_delete_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortable',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='visitortable',
            name='visiting_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
